### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SwanX1** [anseki/vscode-color#101]
- Issue Type: `Performance`
- Extension Name: `vscode-color`
- Extension Version: `0.4.5`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.1`
[anseki.vscode-color-unresponsive.cpuprofile.txt](https://github.com/anseki/vscode-color/files/5114032/anseki.vscode-color-unresponsive.cpuprofile.txt)

**Comment by anseki** [comment]
Hi @SwanX1, thank you for the comment.
You'd better use internal Color Picker of VS Code instead if it's hard to use the extension for your computer.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
