### ISSUE TITLE
How do you create a dialog like that in VS Code?

### ISSUE THREAD

**Issue by jelaplan** [anseki/vscode-color#104]
I'm curious how you created that dialog in VS Code? Most people rely on the Quick Pick in VS Code which often is adequate but as in your Color Picker, a form is sometimes invaluable. My dev team has considered using Webview but the leading opinion is that it is difficult and brings stability issues. 

John laPlante
UX Design Lead, Open Mainframe
jelaplan@gmail.com

**Comment by anseki** [comment]
Hi @jelaplan, thank you for the comment.
The extension uses Electron as VS Code also uses that.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
