### ISSUE TITLE
Trying to Integrate Electron into VSCode Extension

### ISSUE THREAD

**Issue by CJLA** [anseki/vscode-color#106]
Hello @anseki,

We are working on a vscode extension and have not been able to get electron working. We wanted to use color picker as an example but there seems to be some neccessary files missing from the repo that would get it up and running. Do you have any advice on how to get it running, or can you provide some guidance on how to integrate electron? From our research, color picker is the only extension we have found that can do this. Thank you.

**Comment by anseki** [comment]
Hi @CJLA, thank you for the comment.
Sorry, my English is poor.
Do you mean that the Color Picker extension didn't work? Did the installing  fail?

**Comment by CJLA** [comment]
Thank you for your response @anseki,
We do not have a problem with the color picker extension. We are asking for advice.

We are trying to build our own extension (different functions. Not a color picker). We want a new window to pop up using Electron but do not know how to do it. Your extension is the only one we have found that appears to do this.

**Comment by anseki** [comment]
I see.
As you know maybe, VS Code itself also is Electron app. And extensions run as Node.js program.
You can call external programs (including another Electron program) via [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).
If you need, you can implement the "IPC" (interprocess communication) for those programs (process). The Color Picker extension uses standard IO for very simple IPC.

**Comment by CJLA** [comment]
Okay thank you, I will test this out.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by CJLA** [comment]
Alright thanks!
