### ISSUE TITLE
FetchError: Invalid response body while trying to fetch

### ISSUE THREAD

**Issue by dko1905** [anseki/vscode-color#111]
- Extension Version: 0.4.5
- VS Code Version: 1.54.3
- OS Version: `Linux void4ever 5.11.11_1 #1 SMP 1617136041 x86_64 GNU/Linux`
- Node.js Version: v14.16.0
- NPM Version: 6.14.11

Steps to Reproduce:

1. Install extension
2. Use extension in a CSS file

Log (All lines):
[console.log](https://github.com/anseki/vscode-color/files/6289930/console.log)

It seems to be something to do with:
```
/usr/lib/code-oss/resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/combined-stream: Integrity verification failed for sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== (/home/daniel/.npm/_cacache/content-v2/sha512/fa/27/2962e195c5c1c2925bbda526e2b27047a8eb989ee4d2e533cc700cf3419b6a2afcc6865bc4d53c6264f1b640cf1736067db382b325a503057611b68a8602)    at Readable.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:195:14)    at Readable.emit (events.js:223:5)    at /usr/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:92:30    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)    at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)    at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)    at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)    at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)    at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)    at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)    at processImmediate (internal/timers.js:439:21)

```

**Comment by anseki** [comment]
Hi @Dko1905, thank you for the comment.
Try this:
```
cd ~/.vscode-oss/extensions/anseki.vscode-color-0.4.5
npm install
```

**Comment by dko1905** [comment]
Sorry for the late response.
I've run the commands you have supplied, here is the console output:
```
$ cd ~/.vscode-oss/extensions/anseki.vscode-color-0.4.5 
daniel@void4ever ~/.vscode-oss/extensions/anseki.vscode-color-0.4.5 $ npm install                                          
npm WARN deprecated vscode@0.10.7: This package is deprecated in favor of @types/vscode and vscode-test. For more information please read: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== integrity checksum failed when using sha512: wanted sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/combined-stream: Integrity verification failed for sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== (/home/daniel/.npm/_cacache/content-v2/sha512/fa/27/2962e195c5c1c2925bbda526e2b27047a8eb989ee4d2e533cc700cf3419b6a2afcc6865bc4d53c6264f1b640cf1736067db382b325a503057611b68a8602)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2021-04-15T08_19_44_136Z-debug.log
```
The [full log](https://github.com/anseki/vscode-color/files/6316285/2021-04-15T08_19_44_136Z-debug.log) is attached.

**Comment by dko1905** [comment]
I have updated `npm` to version `7.9.0`.
The issue persists.
Here is the "new" output:
```
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== integrity checksum failed when using sha512: wanted sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/combined-stream: sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== integrity checksum failed when using sha512: wanted sha512-+icpYuGVxcHCklu9pSbisnBHqOuYnuTS5TPMcAzzQZtqKvzGhlvE1TxiZPG2QM8XNgZ9s4KzJaUDBXYRtoqGAg== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2021-04-15T08_22_13_309Z-debug.log
```
[2021-04-15T08_22_13_309Z-debug.log](https://github.com/anseki/vscode-color/files/6316303/2021-04-15T08_22_13_309Z-debug.log)

**Comment by anseki** [comment]
Cache data in your computer is broken. Try this:
```
npm cache clean --force
```

**Comment by dko1905** [comment]
I have cleaned npm and run `npm install` successfully.
I then opened vs-code, reinstalled the extension successfully and tried it by moving cursor to a color in a css file and then running `Pick Color` in the command menu (or what it's called in vs-code).
It fails with a new error:
![tmp](https://user-images.githubusercontent.com/44919636/114865275-4af2ba80-9df2-11eb-8b38-2ad9a877f9e4.png)
I then looked in the developer console:
![new1](https://user-images.githubusercontent.com/44919636/114865674-e2f0a400-9df2-11eb-824b-107b356af9ed.png)
That's already a known issue, so I installed `GConf` on my system. Then a new error:
![new2](https://user-images.githubusercontent.com/44919636/114865734-f734a100-9df2-11eb-95c3-f978eeb8897d.png)
This issue seems to have something to do with #90 
I am using electron version `9.4.1_1`.
[full_vscode_log.log](https://github.com/anseki/vscode-color/files/6317716/full_vscode_log.log)

**Comment by dko1905** [comment]
Oh no, I restarted vs code again and I get a new error:
[new_error1.log](https://github.com/anseki/vscode-color/files/6317782/new_error1.log)
May have something to do with [#108](https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209)

**Comment by anseki** [comment]
Your computer has two problems.
1. As you said, new problem was caused by installing different version of npm. This may help you: https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209
2. `libgconf` is required in your computer. Try this: 
```
sudo apt-get install libgconf-2-4
```
And, execute the extension again after installation that.

**Comment by dko1905** [comment]
I have downgraded `npm` and reinstalled gconf.
I'm back to the [this](https://github.com/anseki/vscode-color/issues/111#issuecomment-820371978) issue.

**Comment by anseki** [comment]
Do you mean that the error about `libgconf` was shown again?
If so, the installing was failed maybe.

**Comment by dko1905** [comment]
This error:
![img](https://user-images.githubusercontent.com/44919636/114865734-f734a100-9df2-11eb-95c3-f978eeb8897d.png)
This log:
[log.log](https://github.com/anseki/vscode-color/files/6317782/new_error1.log)

**Comment by anseki** [comment]
That error should be solved by this: https://github.com/anseki/vscode-color/issues/108#issuecomment-774365209
The log means that your NPM was not replaced, it was failed maybe.
Check result of the `npm install npm@6.14.11`.

**Comment by dko1905** [comment]
It succeeded.
```
$ npm --version
6.14.11
```

**Comment by dko1905** [comment]
Maybe I attached the wrong log, I'll attach a new one.

**Comment by anseki** [comment]
Try this:
```
cd ~/.vscode-oss/extensions/anseki.vscode-color-0.4.5
npm install npm@6.14.11
```
(`cd` target is important)

**Comment by dko1905** [comment]
> Try this:

It's installed. I did it again just because.


new image:
![epic (1)](https://user-images.githubusercontent.com/44919636/114898752-ad5bb300-9e12-11eb-9e22-0b45637a86ef.png)
new log:
[log.log](https://github.com/anseki/vscode-color/files/6319300/log.log)

**Comment by dko1905** [comment]
Here is a large image of the log.
![larger](https://user-images.githubusercontent.com/44919636/114899207-0c212c80-9e13-11eb-8297-d65ca6a6d699.png)

**Comment by anseki** [comment]
The issue might be solved by downgrading the glibc in your computer, but I don't know whether this is best solution or not.
Sorry, I can't help you about this.
I think that you had better use internal Color Picker of VS Code instead.

**Comment by dko1905** [comment]
Thank you for the support.

**Comment by anseki** [comment]
:smile:
