### ISSUE TITLE
Unable to pick a color on Windows 8

### ISSUE THREAD

**Issue by Abhirajshri-programmer** [anseki/vscode-color#115]
When I select the color in my code, and press Alt+c p, it doesn't do anything. Even if I try opening the command palette, and typing "Pick color", the same result.

**Comment by anseki** [comment]
Hi @Abhirajshri-programmer, thank you for the comment.
Could you explain more?
Copy this template:
https://raw.githubusercontent.com/anseki/vscode-color/master/.github/ISSUE_TEMPLATE.md

**Comment by Abhirajshri-programmer** [comment]
- Extension Version: 0.4.5 
- VS Code Version: 1.56.2
- OS Version: Windows 8.1

Steps to Reproduce:
1.  When I press Alt+c p, nothing happens.
2. Even if I do the same by using the command palette.

**Comment by anseki** [comment]
Please copy **all** of this template:
https://raw.githubusercontent.com/anseki/vscode-color/master/.github/ISSUE_TEMPLATE.md

**Comment by Abhirajshri-programmer** [comment]
- Extension Version: 0.4.5
- VS Code Version: 1.56.2
- OS Version: Windows 8.1
- Node.js Version: 14.17.0
- NPM Version: 6.14.13

Steps to Reproduce:

1. When I press Alt+c p, nothing happens.
2. Even if I do the same by using the command palette.
Log: no log.

**Comment by anseki** [comment]
Sorry, what does "no log" mean?

**Comment by Abhirajshri-programmer** [comment]
> Sorry, what does "no log" mean?

Meaning I didn't have any log.

**Comment by anseki** [comment]
If really nothing was output in the log list, your VS Code may be broken, because many log lines are output from almost extensions and VS Code itself even if Color Picker is not installed.
VS Code might be restored by re-installing.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
