### ISSUE TITLE
Pick a color not doing anything

### ISSUE THREAD

**Issue by mbaas2** [anseki/vscode-color#116]
I had the "please wait a while for setting up the extension ..."-[issue](https://github.com/anseki/vscode-color/issues/32), but after manually running setup (with NPM), it is gone.
But now, when I call "Pick a color" - nothing happens! (Does it require selection of some CSS or so - I'm simply trying to launch it to see it doing something...)

- Extension Version: 0.4.5
- VS Code Version: : 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

- NPM Version (result of command `npm -v`): 6.4.1

Steps to Reproduce:

1. Alt+C P

Log (All lines): 
[Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 9
console.ts:137 [Extension Host] Try to send IPC message: 10
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: 0

**Comment by anseki** [comment]
Hi @mbaas2, thank you for the comment.
Your GPU driver might have a problem.
Specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

**Comment by mbaas2** [comment]
Thanks - that did the trick!

**Comment by anseki** [comment]
:smile:
