### ISSUE TITLE
Cannot open Pick color

### ISSUE THREAD

**Issue by hoangtm12** [anseki/vscode-color#119]
- Extension Version: v0.4.5
- VS Code Version: 1.62.2
- OS Version: macOS BigSur 11.5.1
- Node.js Version (result of command `node -v`): v17.0.1
- NPM Version (result of command `npm -v`): 8.1.2
- Message error: [processBridge]: Error: Child process already exited.
Steps to Reproduce:
1. Enter: cmd + shift + P
2. Choose Pick Color
I uninstalled it some times and delete file .../.vscode/extensions/anseki.vscode-color-0.4.5 then install it again, but the error is existed. 
Many thanks!

<img width="948" alt="Screen Shot 2021-11-13 at 12 59 07" src="https://user-images.githubusercontent.com/18254022/141607810-2f9e9f36-2364-4f76-801a-5a4495889350.png">
<img width="1035" alt="Screen Shot 2021-11-13 at 13 00 00" src="https://user-images.githubusercontent.com/18254022/141607939-814270c9-dd4e-458f-943e-58de3d30471c.png">

**Comment by anseki** [comment]
Hi @hoangtm12, thank you for the comment.
Could you show me log?
After the error was thrown, click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab, then copy all lines.

**Comment by jdk2** [comment]
I am having the same issue on Fedora Linux. I too have tried reinstalling more than once. I have included a screenshot of the error I get in the console when I try to open the picker, but it complains about a `./extension` file it can't find and sure enough, that is referenced on line 45 of your `package.json` but does not exist in the extensions folder.

![Screenshot_2021-11-17_15-47-33](https://user-images.githubusercontent.com/13594649/142331374-28f26aa0-bea9-4086-adc4-6e2c84949e51.png)

Extension Version: v0.4.5
VS Code Version: 1.62.2
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.22-100.fc32.x86_64

**Comment by anseki** [comment]
Hi @jdk2, thank you for the comment.
That seems to be not the same issue.
Could you make new issue for that?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
