### ISSUE TITLE
Why is the file size extention too much?

### ISSUE THREAD

**Issue by miladghiravani** [anseki/vscode-color#12]
- Extension Version:
- VS Code Version: 1.5.3
- OS Version: Windows 8.1 64-bit
- Node.js Version (result of command `node -v`): v6.5.0
- NPM Version (result of command `npm -v`): 3.10.3

When I going to `%USERPROFILE%\.vscode\extensions` (Extension Locally), vscode-color folder size is too large (upper ~120 Mb)
Why?

**Comment by anseki** [comment]
Hi @miladghiravani,

Actually, the size of the extension is 293KB only.
A few NPM modules that the extension uses are installed into that folder automatically. 
The largest module is electron that is base of VS Code also.

**Comment by miladghiravani** [comment]
@anseki Thanks for answer. But other extensions is lower than 12 Mb.

**Comment by anseki** [comment]
The size of this extension is 293**_KB**_, not MB.
See: https://github.com/anseki/vscode-color#install

**Comment by anseki** [comment]
Please tell me what confused you, instead of closing the issue in silence. Your reaction made me confuse. Please.
I think that of course you know that 293KB is lower than 12MB.
