### ISSUE TITLE
Openning Color Picker Fails with command not found.

### ISSUE THREAD

**Issue by jdk2** [anseki/vscode-color#120]
I am having an issue opening the color picker on Fedora Linux. I have tried reinstalling more than once. I have included a screenshot of the error I get in the console when I try to open the picker, but it complains about a ./extension file it can't find and sure enough, that is referenced on line 45 of your package.json but does not exist in the extensions folder.

- Extension Version: v0.4.5
- VS Code Version: 1.62.2
- Electron: 13.5.1
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Linux x64 5.11.22-100.fc32.x86_64

Steps to Reproduce:

1. Use keyboard shortcut or command pallet to pick a color.
2. Get an error saying command not found and console error shown below.

![Screenshot_2021-11-18_14-44-30](https://user-images.githubusercontent.com/13594649/142514353-fc5784d3-bc33-4f17-aafa-c48828e7d90c.png)
![Screenshot_2021-11-17_15-47-33](https://user-images.githubusercontent.com/13594649/142514307-4ff3c9a1-c2bd-4e3e-9168-8385e5e3968c.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
Activating extension 'anseki.vscode-color' failed: Cannot find module '/home/<user>/.vscode-oss/extensions/anseki.vscode-color-0.4.5/extension'
Require stack:
- /usr/share/codium/resources/app/out/vs/loader.js
- /usr/share/codium/resources/app/out/bootstrap-amd.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js.
```

**Comment by anseki** [comment]
Hi @jdk2, thank you for the comment.
Sorry, I don't know VSCodium well. The issue might be based upon VSCodium.
Try it in official VS Code if you can.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
