### ISSUE TITLE
Electron Update window showing up?

### ISSUE THREAD

**Issue by Elyx0** [anseki/vscode-color#123]
- Extension Version: v0.4.5
- VS Code Version: 
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:58.853Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0

- Node.js Version (result of command `node -v`): v14.17.1
- NPM Version (result of command `npm -v`): 6.14.13

Steps to Reproduce:

1. Opened VScode
2. Saw following popup

<img width="1299" alt="5cfd4ca7ed5732109f6e091a5959810d" src="https://user-images.githubusercontent.com/706218/144194178-71065129-0549-4603-b488-dba38a548d2c.png">

**Comment by anseki** [comment]
Hi @Elyx0, thank you for the comment.
That is strange because the extension is not started yet. That is, your "Steps to Reproduce" means it is only starting VS Code.
Maybe, the extension or something in your computer is broken, try to re-install the extension.

**Comment by anseki** [comment]
Was the issue solved?

**Comment by Elyx0** [comment]
No but I didn't reinstall yet, will report!

**Comment by anseki** [comment]
I see.
Thank you for the information. :smile:
