### ISSUE TITLE
Color picker GUI does not show up but mouse hover exists!

### ISSUE THREAD

**Issue by r4isen1920** [anseki/vscode-color#125]
- Extension Version: `v0.4.5`
- VS Code Version: `1.66.0 (user setup)`
- OS Version: `Windows_NT x64 10.0.22581`
- Node.js Version (result of command `node -v`): `v17.8.0`
- NPM Version (result of command `npm -v`): `8.6.0`

Steps to Reproduce:

1. Highlight a HEX color text selection
2. Run "Pick Color" command from the command palette `CTRL + SHIFT + P`

**Please pay attention to the cursor! It changes as if there was something there but nothing really pops-up.**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43404913/161886757-27a1a65e-7291-482f-a733-f80c34f99f67.gif)

I'm a bit naive to these types of stuff. Please let me know if you need any more necessary info.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
workbench.desktop.main.js:71 [Extension Host] Check version of: electron-prebuilt
workbench.desktop.main.js:71 [Extension Host] Check version of: comma-separated-values
workbench.desktop.main.js:71 [Extension Host] Check version of: js-yaml
workbench.desktop.main.js:71 [Extension Host] Check version of: npm
workbench.desktop.main.js:71 [Extension Host] Check version of: process-bridge
workbench.desktop.main.js:71 [Extension Host] Try to send IPC message: 15
workbench.desktop.main.js:71 [Extension Host] Try to send IPC message: 16
workbench.desktop.main.js:71 [Extension Host] Child process disconnected
workbench.desktop.main.js:71 [Extension Host] Child process exited with code: 0
```

**Comment by r4isen1920** [comment]
Fixed by setting `colorHelper.disableGpu` to `1`.

**Comment by anseki** [comment]
:smile:
