### ISSUE TITLE
No color preview appears

### ISSUE THREAD

**Issue by NickWoodward** [anseki/vscode-color#131]
- Extension Version: 0.4.5
- VS Code Version: 1.66.2
- OS Version: Win10
- Node.js Version (result of command `node -v`): 16.14.0
- NPM Version (result of command `npm -v`): 8.5.0

Steps to Reproduce:

1. Type # and select the color picker

![image](https://user-images.githubusercontent.com/16296682/166438647-865d09d9-72eb-4452-ad45-b4d7992f2608.png)

No preview of the selected color appears? Perhaps I'm doing something wrong?

**Comment by anseki** [comment]
Hi @NickWoodward, thank you for the comment.
Could you explain more?
* What is the "color preview"?
* What is the image in your comment? (That seems to be a color picker of another app such as Adobe Photoshop, MS Excel, or something.)
* What does the "Type # and select the color picker" mean?

**Comment by NickWoodward** [comment]
Hi @anseki - my mistake - that was another color picker that I've now removed!

Although 'Alt+C P' isn't working either. Appreciate the quick reply!

**Comment by anseki** [comment]
I see.
So, could you answer to other questions?

**Comment by NickWoodward** [comment]
Sorry, none of my original questions make sense because it wasn't your extension running - typing # was how the other color picker was executed, and your extension does have a color preview pane

But now that I've uninstalled that other extension, I can't get your dialog box to pop up at all. Either by running `Pick Color` or `Alt+C P`. Neither works.

**Comment by anseki** [comment]
Could you show the log?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by NickWoodward** [comment]
Nothing was coming up in the log, but eventually it threw a couple of errors:

here's the first:

```[Extension Host] Error: Cannot find module 'npm'Require stack:- c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js- c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js- c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\extension.js- c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js- c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js- c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)	at Module._load (node:internal/modules/cjs/loader:832:27)	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)	at Function.i._load (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:32156)	at Function.E._load (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:28749)	at Function.g._load (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:61429)	at Module.require (node:internal/modules/cjs/loader:1059:19)	at h (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)	at getNpm (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:139:15)	at initModule (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)	at getHostCmd (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)	at c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19	at Object.exports.sendRequest (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)	at pickConvert (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)	at exports.pick (c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)	at m._executeContributedCommand (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)	at m.$executeContributedCommand (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)	at i._doInvokeHandler (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)	at i._invokeHandler (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)	at i._receiveRequest (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)	at i._receiveOneMessage (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)	at c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947	at u.invoke (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)	at v.fire (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)	at d.fire (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)	at c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275	at u.invoke (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)	at v.fire (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)	at d.fire (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)	at o._receiveMessage (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)	at c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149	at u.invoke (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)	at v.fire (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)	at v.acceptChunk (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)	at c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995	at Socket.P (c:\Users\Nick\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)	at Socket.emit (node:events:390:28)	at addChunk (node:internal/streams/readable:315:12)	at readableAddChunk (node:internal/streams/readable:289:9)	at Socket.Readable.push (node:internal/streams/readable:228:10)	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)```

**Comment by NickWoodward** [comment]
sorry about the formatting

**Comment by NickWoodward** [comment]
It's gone back to outputting nothing on alt+c p

**Comment by anseki** [comment]
Maybe that is not all of the log.
Try this:
```
cd c:\Users\Nick\.vscode\extensions\anseki.vscode-color-0.4.5
npm install npm@6.14.11
```
And restart VS Code, and run the extension.

**Comment by BadSmailik** [comment]
не работает ваше приложение. Вы хоть ответьте кому не будь

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by snuup** [comment]
I have the same issue. 

![image](https://user-images.githubusercontent.com/61933552/195341295-53f3e5c6-1dd4-4b06-b8d6-aa361bd23141.png)

**Comment by anseki** [comment]
Hi @snuup, thank you for the comment.
See this: https://github.com/anseki/vscode-color/issues/131#issuecomment-1116051791
