### ISSUE TITLE
Color Picker not picking up VS Code theme colour. Dark artefacts when hovering Color Picker window.

### ISSUE THREAD

**Issue by BobbyBabes** [anseki/vscode-color#23]
**Issue :** The Color Picker extension doesn't pick up the styling of the VS Code theme.
I have a dark theme active in VS Code, but Color Picker appears as (its own?) light theme (1st and 2nd screenshot).
Further more, hovering the Color Picker window makes shades of grey appear (2nd screenshot).

- Extension Version: **0.2.2**
- VS Code Version:
```
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version:
**Linux designbox 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux**
- Node.js Version (result of command `node -v`): **v7.4.0**
- NPM Version (result of command `npm -v`): **4.0.5**

Steps to Reproduce:

1. `Alt+C` then `P` in any opened editor window.
2. Wait for colour picker to appear.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
  extensionHost.ts:293 [Extension Host] vscode-icons is active!
  extensionHost.ts:293 [Extension Host] Start child process...
  extensionHost.ts:293 [Extension Host] Check version of: electron-prebuilt
  extensionHost.ts:293 [Extension Host] Check version of: comma-separated-values
  extensionHost.ts:293 [Extension Host] Check version of: js-yaml
  extensionHost.ts:293 [Extension Host] Check version of: process-bridge
2 extensionHost.ts:293 [Extension Host] Try to send IPC message: 1
  extensionHost.ts:293 [Extension Host] Try to send IPC message: 2
  extensionHost.ts:293 [Extension Host] Child process disconnected
  extensionHost.ts:293 [Extension Host] Child process exited with code: 0
```

![vscode-color-picker-extension-not-picking-up-theme-colour_cropped](https://cloud.githubusercontent.com/assets/22870070/21956121/a0cae342-da79-11e6-9f7e-b2a0b3d3df48.png)

![vscode-color-picker-extension-not-picking-up-theme-colour-and-dark-artefacts-when-hovered_cropped](https://cloud.githubusercontent.com/assets/22870070/21956125/af7a4c66-da79-11e6-8122-6c5683e93609.png)

**Comment by anseki** [comment]
Hi @BobbyBabes, thank you for the report.

This is caused by your computer environment and GPU drivers on Linux.
The current Chromium has a bug about the alpha channel and drivers.
At least for the present, unfortunately we can do nothing about this.

**Comment by BobbyBabes** [comment]
Yeah sure. And I have brain damage of course.

**Comment by anseki** [comment]
By v0.3.1, this issue in some environments was solved.
However, those may be not all environments.

**Comment by anseki** [comment]
More options were added, to solve the rendering trouble like this issue.
