### ISSUE TITLE
Error on start the extension

### ISSUE THREAD

**Issue by Vitor83** [anseki/vscode-color#25]
- Extension: 0.2.3
- VS Code: 1.9.1
- MacOS 10.12.3
- Node.js: 7.5.0
- NPM: 4.2.0
- Electron: 1.4.13

Steps to Reproduce:
1. On press opt-c p
2. Show the error (image)
![captura de tela 2017-02-23 as 13 50 52](https://cloud.githubusercontent.com/assets/22767881/23270035/3680b86e-f9d1-11e6-895e-974d9c65af63.png)

```
[Extension Host] Start child process...
extensionHost.ts:282 [Extension Host] Check version of: electron-prebuilt
extensionHost.ts:282 [Extension Host] Check version of: comma-separated-values
extensionHost.ts:282 [Extension Host] Check version of: js-yaml
extensionHost.ts:282 [Extension Host] Check version of: process-bridge
extensionHost.ts:282 [Extension Host] Try to send IPC message: 1
extensionHost.ts:282 [Extension Host] [STDERR]: App threw an error when running [TypeError: Cannot read property 'on' of undefined]
extensionHost.ts:282 [Extension Host] Try to send IPC message: 1
```

**Comment by anseki** [comment]
Hi @Vitor83,

It seems that the Electron in your computer is broken.
Try this:

```
cd ~/.vscode/extensions/anseki.vscode-color-0.2.3
npm uninstall electron-prebuilt
```

And `Pick Color` command on VS Code.

**Comment by Vitor83** [comment]
Hi @anseki,

Thanks for the answer, but the error still persist, I've tried it before, I've uninstalled and reinstalled everything and still got the error

**Comment by anseki** [comment]
The electron and another electron might conflict.
Did you install Electron globally? If so, that should not be installed globally because various apps may not work by the confliction.
Try to remove that. (except there are special reasons)

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt
```

**Comment by Vitor83** [comment]
Sure, when I use electron I only install with '--save-dev', it's not the case.
I just have two electron Apps installed on this Mac VSCode and Atom, I'm missing something maybe other package I really don't know.

**Comment by Vitor83** [comment]
I found it, you were right, I found two node_modules folder on my mac (I don't know why) and both had electron inside, I removed one and bingo!

Thanks a lot for your help, I love this extension

**Comment by anseki** [comment]
I'm glad to be of your help. 😄 
So, the extension works fine?

**Comment by Vitor83** [comment]
Yes working fine, and I tested with electron installed globally and it works too, but I just uninstalled.

**Comment by anseki** [comment]
The "global" path in the process of VS Code might differ from that of your shell.
Your report may help me and someone. Thank you 😄
