### ISSUE TITLE
not work vscode win10

### ISSUE THREAD

**Issue by shine-ace-yj** [anseki/vscode-color#26]
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
Hi @shine-ace-yj,
So, did you mistake something?
Does the extension work in your Win 10?
Or, Is this your first issue in Github?

**Comment by shine-ace-yj** [comment]
The extension was work in my Win 10 ,but i can't use it, This is my first issue in Github, sorry, My question may not be polite；

**Comment by anseki** [comment]
I see.
So, this issue was solved?
Or, can't you use it by another issue?

**Comment by shine-ace-yj** [comment]
No

**Comment by anseki** [comment]
What is no?
