### ISSUE TITLE
[feature] React Native Stylesheets support (styles in js)

### ISSUE THREAD

**Issue by filipsuk** [anseki/vscode-color#27]
Love your plugin! Have you considered supporting react native stylesheets - styles in javascript files? IMHO it would be enough to detect color strings in object literals. Here is a example:

```js
import { StyleSheet } from 'react-native';
...
const textShadow = {
  textShadowColor: '#000000', // <--- HERE
  textShadowRadius: 4,
  textShadowOffset: { width: 0, height: 0 },
  shadowOpacity: 0.5
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'transparent'
  },
  title: {
    color: '#FFFFFF', // <--- HERE
    ...textShadow
  },
  date: {
    color: '#FFFFFF', // <--- HERE
    ...textShadow
  }
});
```
Cheers

**Comment by anseki** [comment]
Hi @filipsuk, thank you for the comment.
So, do you mean that the extension did not work with the your example code?
The extension should work any file type and format. I tried it with the your example code, and that worked fine.
Please report if it doesn't work.

**Comment by filipsuk** [comment]
I don't see the color squares next to the color strings as you have them on screenshots.

From your screenshots: 
![image](https://cloud.githubusercontent.com/assets/6044955/24142399/bc102014-0e26-11e7-9db6-485f01e62be5.png)
Way I see it:
![image](https://cloud.githubusercontent.com/assets/6044955/24142350/9a761f12-0e26-11e7-9332-7eda3c401baf.png)

**Comment by anseki** [comment]
It seems that you misunderstood.
That squares are drawn by VS Code, not extension.
If you want new feature about that squares, send request to [VS Code repository](https://github.com/Microsoft/vscode/issues), not here.
This is "Color Picker for VS Code".
