### ISSUE TITLE
Color picker in React Native files

### ISSUE THREAD

**Issue by DFelten** [anseki/vscode-color#28]
- Extension Version: 0.2.5
- VS Code Version:  1.11.0-insider
- OS Version: Windows 10
- Node.js Version (result of command `node -v`): v6.10.0
- NPM Version (result of command `npm -v`): 3.10.10

I'm creating an app with React Native and there I've got a styles.js like this:
```
export const colors = {
  background: '#F5F2F9',
}
```
or within the normal files:
```
export default StyleSheet.create({
  menuBarButton: {
    backgroundColor: '#F5F2F9',
    height: 40,
    marginLeft: 10
  },
})
```
It would be great if the color picker would also work there.

**Comment by anseki** [comment]
Hi @DFelten, thank you for the comment.
This extension should work any file type and format.
And, I made sure that it works fine with the your example code.

Please report if it doesn't work.
Or, you might not want Color Picker.

**Comment by DFelten** [comment]
Thanks for the answer. I tried it again but it's still not working.

![image](https://cloud.githubusercontent.com/assets/1169185/24195343/a884c94a-0ef9-11e7-9f4d-61a6037826b7.png)

The right one is css, there it's working, but not on the left and the middle one. These files are recognized as JavaScript React.

**Comment by anseki** [comment]
Are you perhaps saying about the small colored square at the left of `#F5F2F9`?
If so, It seems that you mistook a repository. You should comment in [VS Code repository](https://github.com/Microsoft/vscode/issues), not here. This is "Color Picker" repository. Those squares are drawn by VS Code.
It seems a duplicate of https://github.com/anseki/vscode-color/issues/27, https://github.com/anseki/vscode-color/issues/17.

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by SanchitB23** [comment]
Color picker does not show up when `'#fff'` colors are places in quotes, however it shows up when without quotes, in HTML or CSS files This problem mostly occurs in styling react files

**Comment by anseki** [comment]
Hi @SanchitB23 , thank you for the comment.

It seems that you mistook a repository. You should comment in [VS Code repository](https://github.com/Microsoft/vscode/issues), not here. This is "Color Picker" repository. Those squares are drawn by VS Code.
It seems a duplicate of https://github.com/anseki/vscode-color/issues/27, https://github.com/anseki/vscode-color/issues/17.

**Comment by naderhezzy** [comment]
[vscode-color-picker](https://marketplace.visualstudio.com/items?itemName=AntiAntiSepticeye.vscode-color-picker)

Hope this help.

**Comment by anseki** [comment]
Hi @naderhezzy, thank you for the information. :smile:

**Comment by vbpatel5556** [comment]
Hi @naderhezzy , thank you.
