### ISSUE TITLE
Fails on OSX

### ISSUE THREAD

**Issue by Scapal** [anseki/vscode-color#3]
When I try to start the Color Picker, I get an error: `'extension.colorHelper.pick' failed`
VSC Version 0.10.9 (0.10.9)

**Comment by anseki** [comment]
Hi @Scapal, thank you for reporting.
Could you give me these information?:
- Version of Node.js
- When you got that error message, click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab. You might see more information about the error.

**Comment by Scapal** [comment]
Node.js v4.2.6
The Console doesn't really help, there is no other message.

**Comment by anseki** [comment]
I see.
Please try this:

```
cd ~/.vscode/extensions/anseki.vscode-color-0.0.7
npm install
```

(`0.0.7` is version of Color Picker)

Then, some node modules will be installed.
After those modules were installed, restart VS Code.

**Comment by anseki** [comment]
No reply came, and I close this issue.
If not solved, please tell me.
