### ISSUE TITLE
please wait a while for setting up the extension ...

### ISSUE THREAD

**Issue by zhangjialegh** [anseki/vscode-color#32]
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (v7.10.0):
- NPM Version (4.5.0):

Steps to Reproduce:

1. Alt + c p
2. dispaly: please wait a while for settting up the extension...(still flash)

waiting for 30 minutes and still display the :(please wait a while for settting up the extension... ) and still flash.Then I uninstall it and remove the root file and reinstall it and still that.

**Comment by anseki** [comment]
Hi @zhangjialegh, thank you for the report.

Could you please give me more information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by ikzjfr0** [comment]
i have the same issue and it finally comes after a minute. I think it's kind of Chinese Great Wall network problem because it will be working again when I go out of China

**Comment by anseki** [comment]
Hi @ikzjfr0, thank you for the report.
Does this document help you?
[Manual installation NPM modules](https://github.com/anseki/vscode-color#manual-installation-npm-modules)

**Comment by tlaak** [comment]
I encountered the same issue (I'm not in China), but manual npm module installation helped.

**Comment by anseki** [comment]
Hi @tlaak, thank you for the report.
It seems that the issue comes in a place where NPM is blocked like China.
