### ISSUE TITLE
[processBridge]: Error: Cannot find module 'ansi'

### ISSUE THREAD

**Issue by xbeaudet** [anseki/vscode-color#33]
after installing the extension on Visual Studio Code on linux mint 18.1, the first launch pops the error mesage : 
[processBridge]: Error: Cannot find module 'ansi'

node -v : v4.2.6
npm -v : 3.5.2

nod and npm were installed using synaptics (deb depots).
node-ansi installed (0.3.0-2)
node-ansi-color-table installed to (1.0.0-1)

**Comment by anseki** [comment]
Hi @xbeaudet, thank you for the report.

Could you please give me more information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by xbeaudet** [comment]
solved by : https://github.com/anseki/vscode-color/issues/10#issuecomment-270654744

**Comment by anseki** [comment]
Could you please report the solution?

**Comment by somoza** [comment]
```
sudo apt-get remove nodejs npm
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by anseki** [comment]
Hi @somoza, thank you for the report. :smile:

**Comment by PMassicotte** [comment]
Thank you, worked for me.
