### ISSUE TITLE
How we can add dialog in extension

### ISSUE THREAD

**Issue by NumberX** [anseki/vscode-color#35]
I need to add dialog after calling command in my extension , can you tell me how you do it.
Many thanks

**Comment by anseki** [comment]
Hi @NumberX, thank you for the comment.

So, did you try the Color Picker extension? And did that work fine?

**Comment by NumberX** [comment]
yes thats work fine for me ,i would like to do some things for another
project.

Cordialement

2017-05-15 23:32 GMT+01:00 anseki <notifications@github.com>:

**Comment by anseki** [comment]
I see.
You can easily make your extension work as a dialog box like the Color Picker extension.
The approach of the Color Picker extension:

- VS Code is being built with [Electron](https://electron.atom.io/) framework. Therefore all of GUI can be designed and controlled via DOM. That is, you can do anything about GUI via DOM in the Electron app. E.g. show something that works as a dialog box.
- However, VS Code doesn't provide APIs to access to the DOM of its window, and it blocks the accessing to the DOM.
- VS Code extensions are executed on Node.js framework. This means that the extension can execute any external program. That is, the extension can execute additional Electron app.

The Color Picker extension works very simply, [`color-helper.js`](https://github.com/anseki/vscode-color/blob/master/lib/color-helper.js) calls the Electron app that works as a dialog box, and it supports IPC to send and receive the color data.

**Comment by NumberX** [comment]
thanks you so much.

2017-05-17 2:30 GMT+01:00 anseki <notifications@github.com>:

**Comment by anseki** [comment]
This issue seems to have been already solved, and I close it.
