### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [anseki/vscode-color#37]
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
No information was given.
It seems that @Abdullah-AlAttar mistook.
