### ISSUE TITLE
Superfluous error

### ISSUE THREAD

**Issue by alechp** [anseki/vscode-color#4]
When I go to "Color Picker" from the command palette I get the following error:

<img width="897" alt="screen shot 2016-05-12 at 11 45 14 am" src="https://cloud.githubusercontent.com/assets/3058939/15226355/369969b2-1837-11e6-9f26-aa61635e81b6.png">

Clearly has to do with the actual pop-up menu.
When I type hotkey ⌥C C it works .. Displays some options via drop down palette.
When I type hotkey ⌥C P I get the error seen above (i.e. same as choosing "Select Color" from command palette

**Comment by anseki** [comment]
Hi @alechp, thank you for the report.
Could you tell me more information please?
- Except that error message is shown, does the "Pick Color" command (i.e. `⌥C P`) work fine? That is, can you pick a color with the dialog-box? And, does the color you picked be inserted in current code?
- When you run the "Convert Color" command (i.e. `⌥C C`) only, does that error be shown? That is, you start VS Code and run the "Convert Color" command before the "Pick Color" command.
- Which version of the extension and VS Code are you using?
- Please check "Console", and tell me that if message was shown in Console. Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab.

**Comment by alechp** [comment]
@anseki 

`Except that error message is shown, does the "Pick Color" command (i.e. ⌥C P) work fine? That is, can you pick a color with the dialog-box? And, does the color you picked be inserted in current code?` Yes, it works fine besides the error (hence the issue title "superfluous error")

`When you run the "Convert Color" command (i.e. ⌥C C) only, does that error be shown? That is, you start VS Code and run the "Convert Color" command before the "Pick Color" command.`
No, error does not show. Works as expected.

`Which version of the extension and VS Code are you using?`
VS Code: 1.1.0
Extension: 0.1.7

`Please check "Console", and tell me that if message was shown in Console. Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab.`

> Dev Tools::Console log:
> Error: 2016-05-13 11:10:26.875 Electron Helper[13436:1854119] Couldn't set selectedTextBackgroundColor from default ()
>     at /Users/alechp/.vscode/extensions/anseki.vscode-color-0.1.7/node_modules/process-bridge/process-bridge.js:467:34
>     at parseMessageLines (/Users/alechp/.vscode/extensions/anseki.vscode-color-0.1.7/node_modules/process-bridge/process-bridge.js:71:7)
>     at /Users/alechp/.vscode/extensions/anseki.vscode-color-0.1.7/node_modules/process-bridge/process-bridge.js:466:22
>     at Socket.<anonymous> (/Users/alechp/.vscode/extensions/anseki.vscode-color-0.1.7/node_modules/process-bridge/process-bridge.js:371:19)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at Socket.Readable.push (_stream_readable.js:111:10)
>     at Pipe.onread (net.js:531:20)

**Comment by alechp** [comment]
Ignore closed issue. Clicked wrong button. Please see comment above.

**Comment by anseki** [comment]
Thank you @alechp.
Those help me very much.
I will update the extension soon.

**Comment by anseki** [comment]
I updated the extension.
Please try v0.1.8.
