### ISSUE TITLE
Error: electron-prebuilt@0.37.3

### ISSUE THREAD

**Issue by mihail-karimov** [anseki/vscode-color#47]
Editet

Color picker not launching.
![sssa](https://user-images.githubusercontent.com/25096465/27431310-86e78f16-5765-11e7-8da0-ffd7920a3099.png)

**Comment by anseki** [comment]
Hi @mihail-karimov, thank you for the report.
That seems an error messages about `wcwhit`'s extension.

This is "Color Picker for VS Code" repository.

**Comment by mihail-karimov** [comment]
sorry wrong screen and error i'd edited issue. Please check. Thank you.

**Comment by anseki** [comment]
Could you tell me details, please?
See: https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

And also, you should not change previous comments with breaking the conversation flow.
