### ISSUE TITLE
windows not working

### ISSUE THREAD

**Issue by magengbin** [anseki/vscode-color#51]
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
This empty issue is closed.
It seems that @magengbin mistook.
You can report something here if you want.
