### ISSUE TITLE
Color notations not working with sass indented syntax files

### ISSUE THREAD

**Issue by raldred** [anseki/vscode-color#52]
- Extension Version: 0.4.5
- VS Code Version: 1.14.1
- OS Version: MacOS Sierra
- Node.js Version (result of command `node -v`): 6.9.5
- NPM Version (result of command `npm -v`): 3.10.10

Steps to Reproduce:

1. Open a sass file with colors
2. Observe no color notation.
3. Open a scss file with colors
4. Observe color notation working.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
Nothing logged
```

**Comment by anseki** [comment]
Hi @raldred, thank you for the report.
Sorry, What does the "color notation" mean?
Do you mean that e.g. `hsl(1, 2, 3)` is not selected when you do `Pick Color` command?

**Comment by raldred** [comment]
Apologies I should have included a screenshot.
Picking a color works fine with hex, rgb and hsl.

It's just there is autocomplete popup & no small indicator box with the current color in.

SCSS (works fine):
![screenshot 2017-08-10 10 50 05](https://user-images.githubusercontent.com/37096/29165162-c660f0c2-7db9-11e7-8f99-a528dca71e92.png)

SASS (nothing):
![screenshot 2017-08-10 10 45 52](https://user-images.githubusercontent.com/37096/29164985-2ab05442-7db9-11e7-80ab-4b1768d16a1e.png)

**Comment by anseki** [comment]
This is "Color Picker" extension that  shows a dialog box, and "Convert Color".
It seems that you said about "syntax highlight" of VS Code editor.
You should report that to [Microsoft](https://github.com/Microsoft/vscode/issues), not here.

**Comment by raldred** [comment]
Ohh really, I totally assumed the color indicator inline came with this extension sorry for wasting your time.

**Comment by anseki** [comment]
😄

**Comment by ScorpioCoding** [comment]
@raldred I've got the same issue. Did you report the issue to Microsoft ? and do you know which ticket # ?

@anseki  Cool extnsion and sorry for clogging your issue tracker, dude...thnx

**Comment by raldred** [comment]
@ScorpioCoding yes I did, they don't and won't be supporting the indent sass syntax.

**Comment by anseki** [comment]
Hi @raldred,
BTW,
Was the https://github.com/anseki/vscode-color/issues/66 solved?

**Comment by ScorpioCoding** [comment]
@raldred, @anseki    I got an email yesterday from the guys at VSCode that they are not responsable for the issue due to the fact that SASS (not scss) is not supported by them. Due to the fact that SASS an external language is. And they advise me to relay the isssue to them.
OK, but hoe do I relay the issue to,? Who is them?
This is what I call passing the buck around..!!!

**Comment by anseki** [comment]
Hi @ScorpioCoding,

Who sent the email to you?
At least, you should ask that question to one who sent the email (not here) because we don't know that email and its message.
Also, I guess that the SASS is (native) supported by future version of VS Code because many requests about SASS were assigned.
https://github.com/Microsoft/vscode/labels/css-less-sass

**Comment by ScorpioCoding** [comment]
@anseki : my bad sorry dude it wasn't an email sorry, me mixing up twee situations...
What I meant to say there is an issue at microsoft where they comment that they don't support SASS
https://github.com/Microsoft/vscode/issues/36724

**Comment by anseki** [comment]
I see. 😄 
However, @aeschli said that it is supported by extensions.
Also, this extension (Color Picker) already supports SASS.

**Comment by aeschli** [comment]
In order to get color decorators in SASS file, SASS extensions need to provide a [colorDecorator](https://github.com/Microsoft/vscode/blob/a376041e1f445bba7b38f2d60c2881723a4914c6/src/vs/vscode.d.ts#L5961).
Please file an issue against the SASS extension you use.

**Comment by anseki** [comment]
Hi @aeschli, thank you for the advice.
@ScorpioCoding, in any case, this is a repository of Color Picker extension, you should report an issue about VS Code or an extension to those repositories, not here.

**Comment by ScorpioCoding** [comment]
@aeschli Sass extension, ok now you've lost me.  
I just did a sass -v and got Sass 3.5.5 (Bleeding Edge)
How do I determine which Sass extension to file an issue against.?

**Comment by ScorpioCoding** [comment]
@aeschli 
Ok this is my sass situation on my Win10 pro
1. Installed Ruby -> gem install Sass
2. In VSCode I've got 3 extensionsthat handle Sass
   - Sass from Robin Bently
   - Sass Fromatter from Sasa Jovanovic Spuki
   - Style Formatter from dweber019  (missed one)
So to whom do I send the issue to ??
Or Am I better off installing different extensions ?

**Comment by aeschli** [comment]
@ScorpioCoding That would be Sass from Robin Bently then: https://github.com/robinbentley/vscode-sass-indented/issues

**Comment by ScorpioCoding** [comment]
@aeschli : OK : Got it thanks, but last couple of questions...
And yes I do now this is the wrong place for this but...
1) Am I better of looking for a different extension if yes any suggestions?
2) Why doesn't Microsoft support the real Sass language and only Sassy css?

**Comment by aeschli** [comment]
@ScorpioCoding Sorry, I'm not a Sass user myself and therefore don't have any tips on which the best extension.
Our team has a limited number of developer and we need to focus on the languages we use ourselves. We're very happy that people from the community help us, and also want to encourage external extensions. Let's help them with good feedback!
