### ISSUE TITLE
 Request textDocument/documentHighlight failed.

### ISSUE THREAD

**Issue by imgwho** [anseki/vscode-color#54]
- Extension Version:0.4.5
- VS Code Version:1.15.0
- OS Version:win10  15063.540
- Node.js Version (result of command `node -v`):8.3.0
- NPM Version (result of command `npm -v`):5.3.0

Steps to Reproduce:

 when i type ctrl+shift+p  then  pick color

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
Not a Valid CSS selector
e.onUnexpectedError @ workbench.main.js:29
(anonymous) @ workbench.main.js:29
e.onUnexpectedExternalError @ workbench.main.js:28
t.onUnexpectedExternalError @ workbench.main.js:28
(anonymous) @ workbench.main.js:28
v @ workbench.main.js:28
enter @ workbench.main.js:28
_run @ workbench.main.js:28
_error @ workbench.main.js:28
v @ workbench.main.js:28
enter @ workbench.main.js:28
_run @ workbench.main.js:28
_error @ workbench.main.js:28
(anonymous) @ workbench.main.js:28
done @ workbench.main.js:28
v @ workbench.main.js:28
enter @ workbench.main.js:28
_run @ workbench.main.js:28
_error @ workbench.main.js:28
e.resolveErr @ workbench.main.js:28
f @ workbench.main.js:28
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:29 [Extension Host] Start child process...
workbench.main.js:29 [Extension Host] Check version of: electron-prebuilt
workbench.main.js:29 [Extension Host] Check version of: comma-separated-values
workbench.main.js:29 [Extension Host] Check version of: js-yaml
workbench.main.js:29 [Extension Host] Check version of: process-bridge
workbench.main.js:29 [Extension Host] Try to send IPC message: 3
workbench.main.js:29 [Extension Host] Try to send IPC message: 4
workbench.main.js:29 [Extension Host] Child process disconnected
workbench.main.js:29 [Extension Host] Child process exited with code: 0
```
![20170812144936.png](https://i.loli.net/2017/08/12/598ea638aa281.png)

**Comment by anseki** [comment]
Hi @imgwho, thank you for the report.
That error "Request textDocument/documentHighlight failed" is not a message by this Color Picker extension.
That seems to be related to TS bug.
https://github.com/Microsoft/vscode/issues?q=is%3Aissue%20%22Request%20textDocument%22

***Irrespective of the error message,*** if the Color Picker dialog box is not shown, your GPU driver might have a problem.
Try to specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

**Comment by imgwho** [comment]
@anseki  oh you are awesome !
 i use this setting "colorHelper.disableGpu=1"  and it success
but i have a little another problem: can i modify shortcuts alt + c p?
because it is conflict of this extension:[Git Lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens):

> Adds a Show Commit File Details command (gitlens.showQuickCommitFileDetails) with a shortcut of alt+c to show a file commit details quick pick menu of the most recent commit of the active file

anyway  thx  a lot again~~

**Comment by anseki** [comment]
Yes, of course you can change the key bindings.
See:
https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by anseki** [comment]
No reply came but I guessed that the issue was already solved, and I close this issue.
