### ISSUE TITLE
Support Visual Studio .vssettings 0xABGR format

### ISSUE THREAD

**Issue by uday0408** [anseki/vscode-color#57]
- Extension Version: 2.3.0
- VS Code Version: 1.15.1
- OS Version: macOS Sierra
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Visual Studio .vssettings file uses 0xABGR format. Can this format be supported also?

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
Hi @uday0408, thank you for the comment.

Yes, of course I will consider supporting that if many requests come.
Also, you can convert the format with supported format.

For example, a case of `#RRGGBB` and `XBGR`.

- After loading a file, replace `0x00([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})` with `#$3$2$1`. (use RegExp)
- Before saving a file, replace `#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})` with `0x00$3$2$1`. (use RegExp)

**Comment by anseki** [comment]
No reply came. I close this issue.

**Comment by uday0408** [comment]
I am following your temporary solution for picking colors. For coloring the
hex code itself, I have written my own extension.

thanks
Uday
