### ISSUE TITLE
Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by daviholandas** [anseki/vscode-color#60]
- Extension Version:latest
- VS Code Version:latest
- OS Version:Sierra
- Node.js Version (result of command `node -v`): v6.11.4
- NPM Version (result of command `npm -v`):3.10.10

Steps to Reproduce:

1. initialization first time.
![captura de tela 2017-10-05 as 04 38 17](https://user-images.githubusercontent.com/26368905/31215720-0a3cdf06-a987-11e7-80e9-be3628161156.png)

![captura de tela 2017-10-05 as 04 16 27](https://user-images.githubusercontent.com/26368905/31215625-a6505464-a986-11e7-9c77-7c0a06db3d38.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by anseki** [comment]
Hi @daviholandas.

That error means that your network environment has problem like proxy settings.
You should configure your computer and your network environment to make NPM work fine.
For example:

```
npm set strict-ssl false
```

**Comment by anseki** [comment]
No reply came. I close this issue.
