### ISSUE TITLE
[FEATURE] Support vscode preview color

### ISSUE THREAD

**Issue by dotnetCarpenter** [anseki/vscode-color#63]
Would it be possible to support the little color preview box in front of the color for color systems not supported by vscode? With Color Picker we can choose HSLA colors, which is great, but since vscode doesn't support showing HSLA colors, the little preview box is always black which is confusing.

![screen shot 2017-11-13 at 15 46 52](https://user-images.githubusercontent.com/43763/32731380-f4236c2c-c889-11e7-895b-c49c2c1f88f9.png)

- Extension Version: 0.4.5
- VS Code Version: 1.18.0
- OS Version: OS X 10.11.6 
- Node.js Version (result of command `node -v`): v8.9.1
- NPM Version (result of command `npm -v`): 5.5.1

Steps to Reproduce:

1.  Open a .css file
2. Use the Color Picker to choose a color and choose HSLA
3. Observe that the small color preview box is always black

**Comment by anseki** [comment]
Hi @dotnetCarpenter, thank you for the comment.

That color preview box is shown by VS Code. And any API to do something about the box is not supported by current version of VS Code.
Therefore, unfortunately, we can do nothing now.
If you want it, you should request that to [VS Code team](https://github.com/Microsoft/vscode/issues).

**Comment by dotnetCarpenter** [comment]
In fact I think it's a bug.. I've posted an issue over at vscode.

**Comment by anseki** [comment]
😄
