### ISSUE TITLE
Default color picker not showing up

### ISSUE THREAD

**Issue by MrPickles2009** [anseki/vscode-color#64]
- Extension Version: 0.4.5
- VS Code Version: 1.18.0
- OS Version: Windows 10 64-bit Version 1703
- Node.js Version (result of command `node -v`): v6.9.5
- NPM Version (result of command `npm -v`): 4.2.0

Steps to Reproduce:

1. Scroll over any color code and this color picker appears:
![](https://user-images.githubusercontent.com/20229190/32916200-544931fc-cae9-11e7-9e6f-1b0502a0a1e7.png)
2. Settings are set to:
```
"colorHelper.disableGpu": 1,
"colorHelper.disableShadow": true,
"colorHelper.disableTransparent": true,
"colorHelper.pickerForm": "default"
```
... so I've gone through the troubleshooting steps.

3. Expecting to see the following:
![](https://raw.githubusercontent.com/anseki/vscode-color/master/s-default.png)

**Comment by anseki** [comment]
Hi @MrPickles2009, thank you for the comment.

Sorry, my English is poor.
Do you mean that you want to disable the default color picker (i.e. the first picture you indicated) that is shown by VS Code?
Or, do you mean that Color Picker that is this extension is not shown when you executed `Pick Color` command?

**Comment by MrPickles2009** [comment]
ok wow. don't know how I missed that in the documentation 😂
Just ran ```Pick Color``` and it worked...

**Comment by anseki** [comment]
I see. 😄 
It is better for you to remove the `colorHelper.*` settings for the troubleshooting.
