### ISSUE TITLE
can not use in react jsx

### ISSUE THREAD

**Issue by denghui1010** [anseki/vscode-color#65]
- Extension Version:0.4.5
- VS Code Version:1.19.1
- OS Version:Mac OS 10.12.6
- Node.js Version (result of command `node -v`):6.9.4
- NPM Version (result of command `npm -v`):5.5.1

Steps to Reproduce:

can not use in react jsx
like this:
`const styles = StyleSheet.create({
  container: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  root: {
    position: 'absolute',
    right: 24,
    left: 24,
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius:8,
    backgroundColor: '#ffffff',
  }
});`

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
```

**Comment by anseki** [comment]
Hi @denghui1010, thank you for the comment.

I confirmed that the extension worked fine in the code you indicated.
So, what does "can not use" you said mean? Do you mean that `Pick Color` command doesn't work?

**Comment by denghui1010** [comment]
Preview color works in .css but not works in .js   `Pick color` command can use in .css and .js
![image](https://user-images.githubusercontent.com/6003030/34282021-99bfc072-e6fd-11e7-838a-7ea1e379f68d.png)

**Comment by anseki** [comment]
What is preview color?
Do you say about a small box on the left of `#dbc9c9`?

**Comment by denghui1010** [comment]
@anseki   yes

**Comment by anseki** [comment]
I see.
That preview box is shown by VS Code, not the extension.
You should report this issue to [VS Code team](https://github.com/Microsoft/vscode/issues), not here.

**Comment by denghui1010** [comment]
@anseki e...   ok, I make a mistake, close this issue

**Comment by anseki** [comment]
😄
