### ISSUE TITLE
Got error when open color picker on stylus file

### ISSUE THREAD

**Issue by jtjoo** [anseki/vscode-color#69]
- Extension Version: 0.4.5
- VS Code Version: 1.20.0
- OS Version: macOS High Sierra
- Node.js Version (result of command `node -v`): v9.3.0
- NPM Version (result of command `npm -v`): 5.6.0

Steps to Reproduce:

1. I pressed `Cmd+Shift+P` and selected `Pick Color` and hit `Enter` on Stylus
2. And I got error like below.

![2018-02-12 12 21 28](https://user-images.githubusercontent.com/10439318/36074971-e208256c-0f8a-11e8-824f-ab0333aeb2b3.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)

`There was no log.`

**Comment by jtjoo** [comment]
I ran this again and I got color picker window. Hmm that was strange. Anyway, my problem solved ;)

**Comment by anseki** [comment]
Hi @jtjoo, thank you for the report.
😄
