### ISSUE TITLE
commands `ColorPick` not found.

### ISSUE THREAD

**Issue by luozhihua** [anseki/vscode-color#71]
- Extension Version: v0.4.5
- VS Code Version: 1.23.1
- OS Version: MacOS Latest
- Node.js Version (result of command `node -v`): 9.0
- NPM Version (result of command `npm -v`): 5.0

Steps to Reproduce:

1.  press `option + C`
2. commands `ColorPick` not found.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
dd
```

**Comment by anseki** [comment]
Hi @luozhihua, thank you for the comment.

The command is `Pick Color`, not `ColorPick`.
See: https://github.com/anseki/vscode-color

**Comment by anseki** [comment]
No reply came. I close this issue. :cry:
