### ISSUE TITLE
Child process IPC message fails on Windows - BTW why soooo big for a color picker (137MB)

### ISSUE THREAD

**Issue by vhanla** [anseki/vscode-color#72]
- Extension Version: 0.4.5
- VS Code Version: 1.23.1
- OS Version: Windows 10 x64
- Node.js Version (result of command `node -v`): v10.0.0
- NPM Version (result of command `npm -v`): 6.0.1

Steps to Reproduce:

1. Start, restart, uninstall, reinstall
2. Invoke Pick Color from Command Palette (ctrl+shift+p)
3. I doesn't do anything

I even did `npm install` from extension's directory. It was 121MB then 137MB in size. So big for a color picker IMHO. Maybe you can opt out electron and use FreePascal to create a multiplatform picker or any other programming language. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Check version of: electron-prebuilt
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Check version of: comma-separated-values
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Check version of: js-yaml
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Check version of: process-bridge
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Try to send IPC message: 1
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Try to send IPC message: 2
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Child process disconnected
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Child process exited with code: 0
```

**Comment by anseki** [comment]
Hi @vhanla, thank you for the report.

As far as I see your report, it seems that the child process IPC message did not fail. Why you thought that?
Could you give me more details?

If you mean that a dialog box was not shown, try to specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

BTW, file size (vsix file) of Color Picker is 296KB (not MB).
Electron is installed in to `node_modules` directory if you don't have it.
Also, VS Code is an app based Electron. That is required for GUI.

**Comment by anseki** [comment]
If you want, please make a new issue about Electron or the file size. Don't comment here about that.

**Comment by vhanla** [comment]
**Thank you, that was it!** 👍 

---

About the size, this is how it uses disk space in my extensions directory: 
![2018-05-18 14_27_47-treesize free](https://user-images.githubusercontent.com/1015823/40254218-374fe72c-5aa8-11e8-9cf4-025af6eeb0b3.png)

I know it is because of Electron (another instance of chromium), not the extension itself (without `node_modules`) xD
![2018-05-18 14_29_32-treesize free](https://user-images.githubusercontent.com/1015823/40254238-46cb08b2-5aa8-11e8-8b7a-123c88da1427.png)

Electron executable here shown belongs to Color Picker (i.e. it is invoked by this extension), VSCode executable is Electron itself (modified of course), two instances (60MB RAM). 
![2018-05-18 14_47_19-color picker](https://user-images.githubusercontent.com/1015823/40254914-e5db6c6a-5aaa-11e8-97bc-5cb1184c93ed.png)

So, Electron from VSCode is not reusable, it has to download the Electron binary (executable electron.exe 70.4MB for this electron-prebuilt version) inside `node_modules`. 

[Electron-Prebuilt is deprecated](https://www.npmjs.com/package/electron-prebuilt), the extension uses version 0.37.3 (March 2016), latest release was April 2017 (v.1.3.15) and last pre-release (v1.6.12) on August 2017. Though, I don't think the vast collection of [CVE](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=electron)s might become a problem, maybe I should be wrong.

Conclusion: 
Extension is awesome, on cold boot it is slow, but afterwards it is fast.
Overall, I don't mind the size NOW, since it is working. However, I still would prefer a native application instead of Electron.

**Comment by anseki** [comment]
Thank you for the reply. :smile:

I also think that you are wrong.
However, as I said, you should not comment here about Electron.
