### ISSUE TITLE
Feature - RGB/RGBA colors as float colors vec3() and vec4()

### ISSUE THREAD

**Issue by kroko** [anseki/vscode-color#73]
Would it be possible to add support for float _color type_ vec3() and vec4()?

[From experience](https://github.com/thomaslindstrom/color-picker/pull/233) extra care should be taken so that color always is float (it includes decimal point - `0` should be `0.0` and `1` should be `1.0`).

Thanks!

**Comment by anseki** [comment]
Hi @kroko, thank you for the proposal.
I think that this extension is now not necessary maybe because VS Code now implements color picker. However I might update the extension when more request. I guess that this feature is not difficult.

**Comment by anseki** [comment]
This feature is not in demand maybe.
And I close this issue.
Thank you for your proposal. :smile:

**Comment by willstall** [comment]
I'd love this feature....

**Comment by anseki** [comment]
Hi @willstall, thank you for your comment.
At the moment, it seems that this feature is not in demand.
However, this is OSS, then you can add the feature if you want.
