### ISSUE TITLE
Color Pic does not open

### ISSUE THREAD

**Issue by xereda** [anseki/vscode-color#74]
- Extension Version: 0.4.5
- VS Code Version: 1.25.0
- OS Version: Linux version 4.17.2-1-ARCH (builduser@heftig-9574) (gcc version 8.1.1 20180531 (GCC)) #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018
- Node.js Version (result of command `node -v`): 10.5.0
- NPM Version (result of command `npm -v`): 6.1.0

The extension is not working. It is not opening.

![pick_color](https://user-images.githubusercontent.com/14337850/42375613-70514820-80f2-11e8-86f9-d29fc363e9ca.gif)

Steps to Reproduce:

1. `CTRL + ALT + P, type pick color`;
2. Select item;

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
console.ts:136 [Extension Host] Start child process...
console.ts:136 [Extension Host] Check version of: electron-prebuilt
console.ts:136 [Extension Host] Check version of: comma-separated-values
console.ts:136 [Extension Host] Check version of: js-yaml
console.ts:136 [Extension Host] Check version of: process-bridge
console.ts:136 [Extension Host] Try to send IPC message: 1
console.ts:136 [Extension Host] Try to send IPC message: 2
console.ts:136 [Extension Host] Try to send IPC message: 3
console.ts:136 [Extension Host] Try to send IPC message: 4
console.ts:136 [Extension Host] Try to send IPC message: 1
console.ts:136 [Extension Host] Try to send IPC message: 2
console.ts:136 [Extension Host] Try to send IPC message: 3
console.ts:136 [Extension Host] Try to send IPC message: 4
console.ts:136 [Extension Host] Child process disconnected
console.ts:136 [Extension Host] Child process exited with code: null
console.ts:136 [Extension Host] Error: Child process exited with code: null
	at /home/jacksons/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:478:19
	at ChildProcess.<anonymous> (/home/jacksons/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
notificationsAlerts.ts:42 [processBridge]: Error: Child process exited with code: null
e.onDidNotificationChange @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.notify @ notificationService.ts:65
e._showMessage @ mainThreadMessageService.ts:84
e._showMessage @ mainThreadMessageService.ts:45
e.$showMessage @ mainThreadMessageService.ts:39
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
c @ ipc.net.ts:81
(anonymous) @ ipc.net.ts:108
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:136 [Extension Host] Error: Child process already exited.
	at sendIpc (/home/jacksons/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:415:31)
	at Timeout.<anonymous> (/home/jacksons/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
notificationsAlerts.ts:42 [processBridge]: Error: Child process already exited.

```

**Comment by xereda** [comment]
I executed ` npm install ` in the extension repo, but it's not work.

![npm-install](https://user-images.githubusercontent.com/14337850/42375772-0aa001e6-80f3-11e8-82d3-c96de493b7e3.gif)

**Comment by anseki** [comment]
Hi @xereda, thank you for the report.

Electron might have been installed globally in your computer. That should not be installed globally because various apps may not work by the confliction.
Try to remove that. (except there are special reasons)

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt
```

**Comment by xereda** [comment]
It's not working.

![eletron](https://user-images.githubusercontent.com/14337850/42378052-3bc8ec8e-80fc-11e8-98be-c9649c369aea.gif)

**Comment by anseki** [comment]
Were multiple versions of Node.js (and NPM) installed in your computer?

**Comment by xereda** [comment]
@anseki yes! I have nvm control manager.

**Comment by anseki** [comment]
At least, it seems that the Electron in a version of Node.js that was activated doesn't work. That might be broken.
Try this:

1. By using NVM, activate a version of Node.js that VS Code uses.
2. Execute commands:

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt

cd ~/.vscode/extensions/anseki.vscode-color-0.4.5
npm uninstall electron-prebuilt
```
3. Call the "Pick Color" command, and wait for a while that installs the Electron.

**Comment by xereda** [comment]
And it did not work.

![electron_pre](https://user-images.githubusercontent.com/14337850/42383394-7a52bea6-810d-11e8-8b55-6b7eda30cf0f.gif)

```
[processBridge]: Error: `options.hostModule` and `package.json` are required.

```

**Comment by anseki** [comment]
That new error message means that the extension is broken. Re-install that.

1. Uninstall the extension.
2. Command to remove NPM cache data.  
`npm cache clean`
3. Command to confirm the cache data were cleared.  
`npm cache ls`
4. Remove Electron cache data in `~/.electron`.
5. Re-install the extension.

**Comment by anseki** [comment]
No reply came. I close this issue.

**Comment by xereda** [comment]
This did not solve the problem. @anseki.

**Comment by anseki** [comment]
Try the steps above.

**Comment by kinoli** [comment]
Same issue here. I don't even have Electron installed on this OSX machine. I just installed the extension, but same error as shown in above video.

<img width="476" alt="screen shot 2018-08-15 at 9 19 44 pm" src="https://user-images.githubusercontent.com/61486/44185347-f9d61a00-a0d0-11e8-8f0c-7a6f9b284db1.png">

**Comment by anseki** [comment]
Hi @kinoli, thank you for the report.
Could you write following information?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jnelken** [comment]
For anyone having this issue, try a simple reinstall. I Suffered the same. I Tried to use the package for the first time, waited for the install (~15s), and then the error message brought me here. After uninstalling and reinstalling, things work smoothly. I can access it with the keyboard shortcut (opt + c, p on Mac) and also from the command menu @kinoli @xereda

**Comment by anseki** [comment]
Hi @jnelken, thank you for the report. :smile:

**Comment by greenais** [comment]
Exactly the same issue here.
All the most recent versions of VSC and CP. Windows 8.1
Reinstalling, clearing cache don't help - first time CP opens with no issue, all subsequent ones fail with error "[processBridge]: Error: Child process already exited."
To note: for several months it worked like a charm, issue started after recent VSC update

UPD: seems to be resoved after adding to config:
```
"colorHelper.pickerForm": "compact2",
"colorHelper.disableGpu": 1,
```

**Comment by anseki** [comment]
Hi @greenais, thank you for the comment.
Sorry, my English is poor.
Do you mean that the issue was solved?

**Comment by greenais** [comment]
Yes, I do.
I suppose disableGpu worked.

**Comment by anseki** [comment]
Thank you @greenais :smile: 
However, it seems that your case is unrelated to this issue.
This issue is a case about installation.
Your case is a problem of your GPU driver.
So, your case is related to the following issues rather than this issue.
https://github.com/anseki/vscode-color/issues/40
https://github.com/anseki/vscode-color/issues/45
