### ISSUE TITLE
Does not work on json files, or CSV files.

### ISSUE THREAD

**Issue by LuisFX** [anseki/vscode-color#76]
- Extension Version: 0.4.5
- VS Code Version: 1.28.2
- OS Version: High Sierra
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Doesn't seem to work on json files, or CSV files. Is this by design?

**Comment by anseki** [comment]
Hi @LuisFX, thank you for the report.
Of course both JSON and CSV are supported.

Could you tell us details?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by LuisFX** [comment]
Extension Version: 0.4.5
VS Code Version: 1.28.2
OS Version: High Sierra
Node.js Version (result of command node -v):v6.14.4
PM Version (result of command npm -v): 3.10.10
Steps to Reproduce: Just installed the extension, and I open a csv file with the following format:

ProductColorName,PrettyColorName,ProductColorCode,WikiColorName,WikiHex
J106084 Action Blue,Action Blue,8751,air force blue (raf),#5d8aa8

Log (All lines): (Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2924 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping
scanNext @ /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2924
_tokenizeString @ /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2814
Grammar._tokenize @ /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2570
Grammar.tokenizeLine2 @ /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2540
e.tokenize2 @ TMSyntax.ts:452
e._updateTokensUntilLine @ textModelTokens.ts:416
e._tokenizeOneLine @ textModelTokens.ts:379
f._revalidateTokensNow @ textModel.ts:1965
f._warmUpTokens @ textModel.ts:1947
f.onBeforeAttached @ textModel.ts:530
t._attachModel @ codeEditorWidget.ts:1284
t.setModel @ codeEditorWidget.ts:385
(anonymous) @ textFileEditor.ts:151
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
then @ winjs.base.js:1587
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
then @ winjs.base.js:1587
enter @ winjs.base.js:762
_run @ winjs.base.js:1089
_setCompleteValue @ winjs.base.js:1073
g @ winjs.base.js:1191
enter @ winjs.base.js:867
_run @ winjs.base.js:1089
_completed @ winjs.base.js:1057
(anonymous) @ textModel.ts:73
emitNone @ events.js:111
emit @ events.js:208
endReadableNT @ _stream_readable.js:1056
_combinedTickCallback @ internal/process/next_tick.js:138
_tickCallback @ internal/process/next_tick.js:180
27/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:2924 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping

**Comment by LuisFX** [comment]
![image](https://user-images.githubusercontent.com/1130772/48019798-23f41280-e0e9-11e8-9090-8f1e12989a4b.png)

**Comment by LuisFX** [comment]
Also, I don't know if this helps, but I had "Color Highlight" installed, and successfully highlights the colors (it's not a color picker). I tried uninstalling it, in case they were conflicting, but no change.

Hope this helps, and thank you!

**Comment by anseki** [comment]
After the installation and opening the CSV file, which command did you execute?

**Comment by LuisFX** [comment]
I'm tried "ALT + C P". In general, I was expecting to just open the file and see color boxes next to the HEX values. Is that the wrong expectation?

**Comment by anseki** [comment]
Did the color picker dialog box be shown?

**Comment by LuisFX** [comment]
no, it doesn't

**Comment by anseki** [comment]
Is the color picker dialog box shown in other than JSON and CSV?

**Comment by anseki** [comment]
No reply came, and I close this issue.
