### ISSUE TITLE
Electron pre-built dependency

### ISSUE THREAD

**Issue by JakeSidSmith** [anseki/vscode-color#79]
Just noticed that this extension comes bundled with electron-prebuilt (which is over 100MB), is this necessary? Could it be moved to a dev dependency?

**Comment by JakeSidSmith** [comment]
Seems that this module is retired: https://github.com/electron-userland/electron-prebuilt

**Comment by anseki** [comment]
Hi @JakeSidSmith, thank you for the comment.
Of course the electron-prebuilt is required, and that can not be moved to the `devDependencies` because it is a framework, it is not a development tool such as transcompiler.
See: https://electronjs.org/

**Comment by anseki** [comment]
No reply came, then I close this issue.

**Comment by JakeSidSmith** [comment]
Hey, @anseki, sorry been too busy to really look into this. I was just surprised to see it as a dependency as VSCode runs on electron anyway.

It seems it's not as easy as I'd imagined: https://github.com/Microsoft/vscode/issues/3011

What is electron needed for in this extension?

**Comment by anseki** [comment]
Hi @JakeSidSmith, thank you for the reply. :smile: 
The electron is used for GUI.
The dialog box that is opened by `Pick Color` command is electron window.

**Comment by anseki** [comment]
If your computer does not have enough space, internal color picker is the better choice.
VS Code already implemented the internal color picker. To use that, you have to install nothing.

**Comment by JakeSidSmith** [comment]
Thank you. I had no idea that existed. 🙂
