### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hhl625830** [anseki/vscode-color#80]
- Issue Type: `Performance`
- Extension Name: `vscode-color`
- Extension Version: `0.4.5`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\HuHongLin\anseki.vscode-color-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by anseki** [comment]
Hi @hhl625830, thank you for the comment.

So, could you please attach your `C:\Users\HuHongLin\anseki.vscode-color-unresponsive.cpuprofile.txt` as it said in [VS Code documentation](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load) and in your issue description?

Also, could you explain about what is the problem?

**Comment by Sebastjano** [comment]
Extension Color Picker 0.4.5 dosn't work on VS Code 1.31.1

**Comment by anseki** [comment]
Hi @Sebastjano, thank you for your report.
However, this is an issue for @hhl625830's case.
Could you make new issue for your case? (Click "New issue" button)

**Comment by anseki** [comment]
No reply came, then I close this issue. :cry:
