### ISSUE TITLE
vscode-color not working

### ISSUE THREAD

**Issue by Sebastjano** [anseki/vscode-color#81]
- Extension Version: 0.4.5
- VS Code Version: 1.31.1
- OS Version: Win 10x64
- Node.js Version (result of command `node -v`): 10.15.2
- NPM Version (result of command `npm -v`): 6.4.1

The extension does not workin SASS files. You can not see any work, nor gives any errors. No signs of life at all. Previously, the extension worked and was very pleased. Help restore expansion.

**Comment by anseki** [comment]
Hi @Sebastjano, thank you for your comment.

+ Which command did you execute?
+ Does the extension work in other than SASS files (e.g. HTML, JavaScript, etc.)?

**Comment by Sebastjano** [comment]
I do not work with color in js, html files and etc. I work with color only in css and sass files. So: everything works perfectly in CSS - shows a small square with a color near the color abbreviation, and when i am  hover the cursor on the abbreviation, a color selection window appears and i can easily select another one and replace the current color. Everything is sad with the SASS files - nothing works there (associated with the extension). Previously, the extension worked well, everything was fine. After updating VS Code, the extension has stopped working.  
![snap0001658](https://user-images.githubusercontent.com/12022721/53900337-9dbaef00-403c-11e9-9461-51a5f675fe2f.jpg)
![snap0001659](https://user-images.githubusercontent.com/12022721/53900338-9e538580-403c-11e9-974e-2f8c02d31f53.jpg)

:(

**Comment by anseki** [comment]
The extension works in all files.
Could you answer my question about the command?

**Comment by anseki** [comment]
Was your issue already solved?
