### ISSUE TITLE
Add HSL to color spaces for editing the color

### ISSUE THREAD

**Issue by seanonthenet** [anseki/vscode-color#83]
Please add ability to change HSB to HSL (or add HSL) to be able to have a lightness slider. Would really help selecting shades in the same color.

**Comment by anseki** [comment]
Hi @Spark3000, thank you for your comment.
The Color Picker for VS Code already can change the color notations for the output.
You can specify that by drop-down list in the dialog box.
And also, you can change the color notation of color strings that were written in the editor by the [`Convert Color`](https://github.com/anseki/vscode-color#convert-color) command.

Supported color notations:
+ `hsb()`/`hsba()`
+ `hsl()`/`hsla()`
+ `hwb()`
+ `rgb()`/`rgba()`
+ RGB-Hex 3/4/6/8 digits
+ CSS Named Color
+ `device-cmyk()`
+ `gray()`

See document: https://github.com/anseki/vscode-color

**Comment by seanonthenet** [comment]
Hi. Thanks for the reply. 

Yes, the output notations types are very useful however I would really like the ability to change the selected color using the slider to control the amount of Lightness (instead of Brightness) as an option or a switch (even better). 

It's different from HS(B) / HS (V) and is super useful for selecting shades of a color which complement the existing or previous ones. 

More info on this is [here](https://codeitdown.com/hsl-hsb-hsv-color/) and also Steve Schoger the UI expert talks about [HSL vs HSB](https://twitter.com/steveschoger/status/958718695341281282) a lot. Also Sketch App has also [enabled HSL](https://blog.prototypr.io/new-features-in-sketch-53-8335cd9385d3) in their color picker.

**Comment by anseki** [comment]
That feature requires big changing for UI, then I will examine that when more requests come.
Thank you again for your comment. :smile:
If you want to adjust the lightness now, use the Lab or change the output text as the HSL. (But these have no slider. I know, you want visual UI.)

**Comment by anseki** [comment]
I close this issue for now.
I will examine this feature when more requests come. I still welcome comments.
