### ISSUE TITLE
Add option to convert to RGB 8-bit codes

### ISSUE THREAD

**Issue by tuur29** [anseki/vscode-color#85]
Currently it outputs like `rgb(82.7%, 18.4%, 18.4%)`, instead I would like `rgb(211, 47, 47)`.

- Extension Version: 0.45
- VS Code Version: 1.33.1
- OS Version: Win 10 1809
- Node.js Version (result of command `node -v`): 10
- NPM Version (result of command `npm -v`): 5.6

Steps to Reproduce:

1. Select a color
2. Run `Convert Color`
3. Pick `RGB / TGBA`

**Comment by anseki** [comment]
Hi @tuur29, thank you for your comment.

You can specify style of the notation with the dialog box of `Pick Color` command.

1. Open the dialog box via `Pick Color` command.
2. Select `RGB/RGBA` in the drop-down list.
3. Turn off the `<RGB>%` checkbox.

See document: https://github.com/anseki/vscode-color#convert-color

**Comment by tuur29** [comment]
Aha, thanks for clarifying!

**Comment by anseki** [comment]
:smile:

**Comment by anseki** [comment]
Oops..
Sorry, I mistook `Pick Color` for `Convert Color`.

**Comment by tuur29** [comment]
Oh, but it still works though
