### ISSUE TITLE
Add support for 0xRRGGBB values

### ISSUE THREAD

**Issue by deepnight** [anseki/vscode-color#86]
Hello,

Something that is lacking, for some obscure reason, in all color-picker extensions for VScode is a basic support for 0xRRGGBB color codes. These are used in most languages that are not web-based. 

Would it be possible to add this feature to vscode-color, as it is by far the most advanced & widely used picker for VScode?

Optionaly, having support for 0xRRGGBBAA codes would be amazing :)

**Comment by anseki** [comment]
Hi @deepnight, thank you for your comment.

I think that feature has low demand for now.
However, I will examine that when more requests come.

**Comment by anseki** [comment]
I close this issue for now.
I will examine this feature when more requests come. I still welcome comments.

**Comment by Bettelmage** [comment]
Yep, sorry for the duplicate.
 
So here is another request. I am also really interested in having this feature.

i can feel @deepnight, i am wondering why most extensions seem to be web-focused.
Is it because web developers are more open to and more extensions-savvy?
Are my fellow non-web developers still persisting on their vim-user stereotype? 😉 

Anyways, i'd appreciate if you consider this as a feature for a future release.

Thanks!

**Comment by deepnight** [comment]
For now, everytime I want to edit a 0xrrggbb color, I manually replace the 0x by #, invoke the picker UI, then edit back to 0x format... Which isn't that great ;) And god, as a gamedev, I do that often every day!

**Comment by anseki** [comment]
VS Code started as a source code editor for web-app (front-end).
Therefore many extensions focus on web-app (front-end).
And, many programming languages including non-web language were added as supported language.
For C-lang, you can use also Visual Studio instead of VS Code.

**Comment by xwolf47** [comment]
Hello, I also need this request.
VS Code support for many language edit, so support 0x format is very good for that.

**Comment by anseki** [comment]
Hi @xwolf47, thank you for the comment.
I still welcome comments.

**Comment by Tipyx** [comment]
Like my dear companions above, I totally need too !

**Comment by anseki** [comment]
Hi @Tipyx, thank you for the comment. :smile:
