### ISSUE TITLE
run slowly and ... .

### ISSUE THREAD

**Issue by miladghiravani** [anseki/vscode-color#9]
- Extension Version:
- VS Code Version: 1.5.2
- OS Version: Windows 8.1 64-bit
- Node.js Version (result of command `node -v`): v6.5.0
- NPM Version (result of command `npm -v`): 3.10.3

Steps to Reproduce:
Hi

Have some problems:
1) very slowly to run. (for example when `ctrl+c p` , then after 5 or 6 secound running... .)
2) is better when double click then show palette color instead of `ctrl+c p`

Thank you

**Comment by anseki** [comment]
Hi @mghhgm,

1) Try [`colorHelper.resident` option](https://github.com/anseki/vscode-color#colorhelperresident).
2) Please give me more details. What do you double click? Does the "palette color" mean Color Picker Dialog?

Please make new issue for 2.

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by miladghiravani** [comment]
Hi @anseki,
For example see this video

![ezgif-1978409423](https://cloud.githubusercontent.com/assets/5067331/18865503/7bd81b62-84a8-11e6-805d-bd1aa510a044.gif)

**Comment by anseki** [comment]
Please make new issue for 2.
