### ISSUE TITLE
C Syntax Hex Codes

### ISSUE THREAD

**Issue by Bettelmage** [anseki/vscode-color#91]
Hey,

here a suggestion for improvement:

I am developing in C for embedded devices and currently i am playing around with RGB LED lighting. It seems like there are no Color Pickers around which can generate C Hex Syntax Colors (**0x**FF00FF). What a pity. Maybe a feature for next release? :)

**Comment by anseki** [comment]
Hi @Bettelmage, thank you for the comment.
This seems to duplicate of: https://github.com/anseki/vscode-color/issues/86
Please comment in the issue above if you want.
