### ISSUE TITLE
Color Picker does not show up in VS Code 1.40.1

### ISSUE THREAD

**Issue by DRYN07** [anseki/vscode-color#92]
- Extension Version: 0.4.5
- VS Code Version: 1.40.1
- OS Version: Windows 10 1903
- Node.js Version (result of command `node -v`): 13.0.1
- NPM Version (result of command `npm -v`): 6.12.0

Steps to Reproduce:

1. Select color
2. Start Color Picker
3. Nothing happens

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
console.ts:137 [Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 9
console.ts:137 [Extension Host] Try to send IPC message: 10
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: 0
```

![Video_2019-11-14_134607](https://user-images.githubusercontent.com/29770761/68858619-b60ffd00-06e5-11ea-8b1c-1c404d78235d.gif)

**Comment by anseki** [comment]
Hi @DRYN07, thank you for the comment.
Your GPU driver might have a problem.
Specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

**Comment by DRYN07** [comment]
Oh God that was too easy... Thank you very much :)

**Comment by anseki** [comment]
:smile:
