### ISSUE TITLE
Create my own Palette based on a workspace?

### ISSUE THREAD

**Issue by reinhardjung** [anseki/vscode-color#93]
Hi

I hope this is the right place to ask a Question? :-(
Can i somehow create my own Palette, maybe based on my/a workspace?

Thanx a lot for any Feedback

**Comment by anseki** [comment]
Hi @reinhardjung, thank you for the comment.
The extension supports custom color palettes.
See document: https://github.com/anseki/vscode-color#color-palettes

**Comment by reinhardjung** [comment]
coool!
Great Ext. fast Support -  i love it :-)

But is do . not really understand how to use it:
On my Mac i got: "colorHelper.storeDir": "/Users/MYUSERNAME/Local Sites/colorPalette",
Should it not be there some File etc, where i can add my Palette/Colors?

**Comment by anseki** [comment]
Of course you can change the `colorHelper.storeDir`.

**Comment by reinhardjung** [comment]
ok, but all i got for now is:
"colorHelper.storeDir": "/Users/MYUSERNAME/Local Sites/colorPalette",
What else do i need?
How can i access my Custom Palette?
(I can't choose it from the selectbox?)

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to know how to create custom color palettes?

**Comment by reinhardjung** [comment]
Yes please and how to use it.
Now i just got this: "colorHelper.storeDir": "/Users/MYUSERNAME/Local Sites/colorPalette",

**Comment by anseki** [comment]
Of course I can tell that.
Before that, did you read this? : https://github.com/anseki/vscode-color/issues/93#issuecomment-569828097

**Comment by reinhardjung** [comment]
Yes, sure but i still do not get it :-(

**Comment by anseki** [comment]
Do you mean that you have read the document (file name: `README.md`, title: "Color Palette for VS Code Color Picker extension")?
Please tell me which point that you couldn't understand in the document.

**Comment by reinhardjung** [comment]
I can't see my Palette: /Users/reinhardjung/Local Sites/colorPalette/cloudmeister.palette.json
![Bildschirmfoto 2019-12-31 um 05 33 10](https://user-images.githubusercontent.com/298616/71610178-305de900-2b8f-11ea-82d9-40c905474536.png)

**Comment by reinhardjung** [comment]
argh. Some Caching Errors ... fixed :-)
Thanx a lot for helping me!!!!

**Comment by anseki** [comment]
Sorry, do you mean that the issue was solved?
If so, could you close this issue?
