### ISSUE TITLE
It just doesn't work on VSCode 1.43.2, Windows 10 x64

### ISSUE THREAD

**Issue by dodancs** [anseki/vscode-color#96]
- Extension Version: 0.4.5
- VS Code Version: 1.43.2
- OS Version: Windows_NT x64 10.0.18363
- Node.js Version (result of command `node -v`): v12.11.1
- NPM Version (result of command `npm -v`): 6.11.3

Steps to Reproduce:

1. Install the extension
2. Press Alt + C P or launch from command palette with Pick Color

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///c%3A/Users/dodan/.vscode/extensions/mtxr.sqltools-0.21.6/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/dodan/.vscode/extensions/redhat.vscode-yaml-0.7.2/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] (node:25536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] (node:25536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] Start child process...
console.ts:137 [Extension Host] Check version of: electron-prebuilt
console.ts:137 [Extension Host] Check version of: comma-separated-values
console.ts:137 [Extension Host] Check version of: js-yaml
console.ts:137 [Extension Host] Check version of: process-bridge
console.ts:137 [Extension Host] Try to send IPC message: 1
console.ts:137 [Extension Host] Try to send IPC message: 2
console.ts:137 [Extension Host] Child process disconnected
console.ts:137 [Extension Host] Child process exited with code: 0
```

Not sure why it doesn't work and I did not see even anyone else complain. I tried it months before, and did not work back then.

Please help?

**Comment by anseki** [comment]
Hi @dodancs, thank you for the comment.
Your GPU driver might have a problem.
Specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

**Comment by dodancs** [comment]
> Hi @dodancs, thank you for the comment.
> Your GPU driver might have a problem.
> Specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.

Thank you! This helped me, and the plugin finally works!

**Comment by dodancs** [comment]
BTW: I have a GTX 1060 6GB, with 442.74 driver from nvidia. I am now updating to the latest: 445.75. I will check whether this helps.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by dodancs** [comment]
After updating the driver, it still did not fix the issue, and I need to use the disableGpu option. Thank you for the fix. Hopefully you will be able to resolve the GPU issue in the future! Have a nice day!

**Comment by anseki** [comment]
Thank you for the report. 
Yes, as I said, it seems that your GPU driver has a problem.
