### ISSUE TITLE
Showing the UI is to slow and tedious

### ISSUE THREAD

**Issue by schroef** [anseki/vscode-color#98]
- Extension Version: 0.4.5
- VS Code Version:  1.45.0
- OS Version: 10.11.6 osx

Using that alt + c + p is to tedious, after that I need to click again before it shows. WHy not s single shortcut. Another issue, why does it take so long to show?

**Comment by anseki** [comment]
Hi @schroef, thank you for the comment.
The performance of the UI that based on Electron depends on environment.
Only first starting might be time consuming work for your computer.

Could you make new issue for another topic after close this issue if it was solved?

**Comment by schroef** [comment]
I'll check it again and will update t
With different post

**Comment by anseki** [comment]
Maybe, you had better use internal Color Picker of VS Code instead of the extension because the Electron seems to be high-load for your computer.

**Comment by doglez** [comment]
Hello, I have a problem with Color Picker, it doesn't work with Alt + C + P or Ctrl + Shift + P and I write Pick Color.

This is my information:
VSC Version: 1.45.1
OS: Linux Ubuntu 20.04lts x64 5.4.0-29-generic snap
Color Picker: Version: 0.4.5

**Comment by anseki** [comment]
Hi @danilogonzalez-mcs, thank you for the comment.
Could you make new issue for another topic?

**Comment by doglez** [comment]
> Hi @danilogonzalez-mcs, thank you for the comment.
> Could you make new issue for another topic?

Ok sorry

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
